import OpenAI from 'openai';
import { getConfig } from '../lib/config';
import { getLogger } from '../lib/logger';

const logger = getLogger().child({ module: 'ai-service' });

interface CompletionConfig {
  systemPrompt: string;
  model: string;
  temperature: number;
  maxTokens: number;
}

interface CompletionResult {
  content: string;
  model: string;
  tokensUsed: {
    prompt: number;
    completion: number;
    total: number;
  };
}

export class AIService {
  private client: OpenAI | null = null;

  constructor() {
    const config = getConfig();
    if (config.openai.enabled) {
      this.client = new OpenAI({ apiKey: config.openai.apiKey });
      logger.info('OpenAI client initialized');
    } else {
      logger.info('OpenAI not configured — using mock mode');
    }
  }

  async complete(prompt: string, config: CompletionConfig): Promise<CompletionResult> {
    if (!this.client) {
      return this.mockComplete(prompt, config);
    }

    try {
      logger.debug({ model: config.model, promptLength: prompt.length }, 'Calling OpenAI');

      const response = await this.client.chat.completions.create({
        model: config.model,
        messages: [
          { role: 'system', content: config.systemPrompt },
          { role: 'user', content: prompt },
        ],
        temperature: config.temperature,
        max_tokens: config.maxTokens,
      });

      const choice = response.choices[0];
      const usage = response.usage;

      const result: CompletionResult = {
        content: choice?.message?.content ?? '',
        model: response.model,
        tokensUsed: {
          prompt: usage?.prompt_tokens ?? 0,
          completion: usage?.completion_tokens ?? 0,
          total: usage?.total_tokens ?? 0,
        },
      };

      logger.info(
        { model: response.model, tokens: result.tokensUsed.total },
        'OpenAI completion successful',
      );

      return result;
    } catch (err) {
      logger.error({ err }, 'OpenAI API error');
      throw err;
    }
  }

  /**
   * Mock completion for demo/development when no API key is set.
   */
  private async mockComplete(prompt: string, config: CompletionConfig): Promise<CompletionResult> {
    // Simulate API latency
    await new Promise((resolve) => setTimeout(resolve, 200 + Math.random() * 300));

    const promptTokens = this.estimateTokens(config.systemPrompt + prompt);
    const mockContent = this.generateMockContent(prompt);
    const completionTokens = this.estimateTokens(mockContent);

    logger.debug({ model: config.model, mock: true }, 'Mock completion generated');

    return {
      content: mockContent,
      model: `${config.model}-mock`,
      tokensUsed: {
        prompt: promptTokens,
        completion: completionTokens,
        total: promptTokens + completionTokens,
      },
    };
  }

  /**
   * Rough token estimation (~4 chars per token).
   */
  estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
  }

  /**
   * Generate mock content based on prompt keywords.
   */
  private generateMockContent(prompt: string): string {
    const lowerPrompt = prompt.toLowerCase();

    if (lowerPrompt.includes('outline')) {
      return [
        '# Blog Post Outline',
        '',
        '## 1. Introduction',
        '- Hook the reader with a compelling statistic',
        '- Introduce the main topic and its relevance',
        '- Preview the key points to be covered',
        '',
        '## 2. Background & Context',
        '- Historical perspective on the topic',
        '- Current state of the industry',
        '- Why this matters now',
        '',
        '## 3. Key Insights',
        '- First major point with supporting evidence',
        '- Second major point with real-world examples',
        '- Third major point with expert opinions',
        '',
        '## 4. Practical Applications',
        '- Step-by-step implementation guide',
        '- Tools and resources recommended',
        '- Common pitfalls to avoid',
        '',
        '## 5. Conclusion',
        '- Summarize key takeaways',
        '- Call to action for readers',
        '- Future outlook',
      ].join('\n');
    }

    if (lowerPrompt.includes('blog') || lowerPrompt.includes('write')) {
      return [
        'This is a comprehensive blog post generated by the AI workflow platform.',
        '',
        'In today\'s rapidly evolving technological landscape, staying ahead of the curve requires',
        'both strategic thinking and practical execution. This article explores the key principles',
        'that drive successful outcomes in modern software development and AI integration.',
        '',
        'The first thing to understand is that effective workflows are the backbone of any',
        'productive team. By automating repetitive tasks and leveraging AI capabilities,',
        'organizations can focus their human talent on creative and strategic work.',
        '',
        'Key benefits include improved efficiency, reduced error rates, and faster time-to-market',
        'for new products and features. The data consistently shows that teams adopting workflow',
        'automation see 40-60% improvements in productivity.',
        '',
        'In conclusion, the future belongs to organizations that can effectively orchestrate',
        'AI-powered workflows while maintaining human oversight and creativity at the helm.',
      ].join('\n');
    }

    return `Mock AI response for prompt: "${prompt.slice(0, 100)}..."\n\nThis is a generated response from the workflow platform's mock AI service. Configure OPENAI_API_KEY for real completions.`;
  }
}
